version: '3.7'
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: airflowdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_db
    networks:
      - af_mysql
    volumes:
      - ./sql/sakila-schema.sql:/docker-entrypoint-initdb.d/init.sql
      - .:/opt/mysql_file
  airflow:
    build: ./airflow_config
    depends_on:
      - db
    networks:
      - af_mysql
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: airflowdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_db
    init: true
    volumes:
      - ./dags:/root/airflow/dags
      - ./logs:/root/airflow/logs
      - .:/opt/code
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    networks:
      - af_mysql
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
networks:
  af_mysql: